language: node_js
node_js:
  - 10
cache:
  npm: true
  directories:
    - ~/.cache
before_install:
  - export CHROME_BIN=chromium-browser
install:
  - npm ci
script: node_modules/karma/bin/karma start karma.conf.js --single-run
  - npm run test
  - npm run e2e
